from langgraph.graph import StateGraph, START, END
from typing import TypedDict, Annotated, Tuple, List, Literal
from src.yt_rag.components.data_loader import DataLoader
from src.yt_rag.components.embedding import EmbeddingManager
from src.yt_rag.components.vectorstore import FaissVectorStore
import numpy as np
from src.yt_rag.components.search import RAGSearch
import os

os.environ['LANGCHAIN_PROJECT'] = "YT_RAG_langgraph"

class RAGState(TypedDict):
    """
    The state of the system throughout the workflow
    """
    video_url: Annotated[str, "the youtube video url"]
    video_id: Annotated[str, "video id extracted from url"]
    query: Annotated[str, "user's query"]
    video_data: Annotated[List[dict[str, str]], "fetch video data using api and preprocess"]
    chunks: Annotated[list[dict[str, str]], "chunks created after semantic chunksing."]     # in the form of a dict with keys (text, start time and end time)
    embeddings: Annotated[np.array, "embeddings for the chunks"]
    vector_store: Annotated[bool, "True if vector store exists, False otherwise"]
    context: Annotated[str, "most relevant context fetched using rag search"]
    answer: Annotated[str, "Answer generated by llm"]
    time_stamps: Annotated[List[Tuple], "Timestamps of top k results"]

# functions
def fetch_video_id(state: RAGState) -> RAGState:
    # extracts the video id from the url
    loader = DataLoader(url = state['video_url'])
    video_id = loader.video_id

    return {"video_id": video_id}

def check_vector_store(state: RAGState) -> Literal["search_vector_store", "fetch_video_data"]:
    # checks if vectorstore already exists, if true routes to search vectorstore directly. If false, then builds the complete vectorstore
    persist_dir = "faiss_store"
    existing_vector_stores = os.listdir(persist_dir)
    if state['video_id'] in existing_vector_stores:
        return "search_vector_store"
    else:
        return "fetch_video_data"

def fetch_video_data(state: RAGState):
    # fetches video data using yt transcript api
    loader = DataLoader(url = state['video_url'])
    video_data = loader.fetch_video_data()
    return {'video_data': video_data}

def create_chunks(state: RAGState):
    # creates semantic chunks
    loader = DataLoader(url = state['video_url'])
    chunks = loader.create_semantic_chunks(video_data= state['video_data'])
    return {"chunks": chunks}

def generate_embeddings(state: RAGState):
    # generate embeddings
    embedding_manager = EmbeddingManager()
    embeddings = embedding_manager.generate_embeddings(chunks = state['chunks'])
    return {"embeddings": embeddings}

def build_vector_store(state: RAGState):
    # builds and saves faiss store
    faiss_store = FaissVectorStore(video_id=state['video_id'])
    faiss_store.add_embeddings(embeddings= state['embeddings'])
    return {"vector_store": True}

def search_vector_store(state: RAGState):
    # searches veror store and fetches most relevent vectors and returns context for llm
    rag_search = RAGSearch(url = state['video_url'])
    context = rag_search.search(query = state['query'])
    return {'context': context}

def generate_response(state: RAGSearch):
    # generates response from llm by providing context and query
    rag = RAGSearch(url = state['video_url'], video_id = state['video_id'])
    response = rag.generate_response(context = state['context'], query = state['query'])
    time_stamps = rag.get_video_timestamps()
    return {"answer": response, "time_stamps": time_stamps}


# define graphstate
graph = StateGraph(RAGState)

# nodes
graph.add_node("fetch_video_id", fetch_video_id)
graph.add_node("fetch_video_data", fetch_video_data)
graph.add_node("create_chunks", create_chunks)
graph.add_node("generate_embeddings", generate_embeddings)
graph.add_node("build_vector_store", build_vector_store)
graph.add_node("search_vector_store", search_vector_store)
graph.add_node("generate_response", generate_response)

# edges
graph.add_edge(START, "fetch_video_id")
graph.add_conditional_edges(
    "fetch_video_id", 
    check_vector_store,
    {
        "search_vector_store": "search_vector_store",
        "fetch_video_data": "fetch_video_data"
    }
)
graph.add_edge("fetch_video_data", "create_chunks")
graph.add_edge("create_chunks", "generate_embeddings")
graph.add_edge("generate_embeddings", "build_vector_store")
graph.add_edge("build_vector_store", "search_vector_store")

graph.add_edge("search_vector_store", "generate_response")
graph.add_edge("generate_response", END)

# compile graph
rag_workflow = graph.compile()

initial_state = {
    "video_url": "https://www.youtube.com/watch?v=ywd-Ve8a8Tc",
    "query": """What is the definition of psycho-history?"""
}

config = {'run_name': "langgraph_full_workflow"}
result = rag_workflow.invoke(initial_state, config=config)

print(result['answer'])

