from src.yt_rag.logger import logging
from src.yt_rag.exceptions import CustomException
from src.yt_rag.components.data_loader import DataLoader
from src.yt_rag.components.embedding import EmbeddingManager
from src.yt_rag.components.vectorstore import FaissVectorStore
from src.yt_rag.utils import load_prompt

import os
import sys
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from typing import List, Tuple

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

class RAGSearch:
    """
    Handles query search in faiss vector store
    """

    def __init__(self, persist_dir:str = 'faiss_store', llm_model:str= "gpt-4o-mini", url:str | None = None, model_name: str = "text-embedding-3-large", video_id:str = None):
        self.persist_dir = persist_dir
        self.url = url
        self.model_name = model_name

        self.video_id = video_id
        self.video_dir = None

        # extract video id
        loader = DataLoader(url= self.url)
        self.video_id = loader.video_id
        if not os.path.exists(self.persist_dir): 
            os.makedirs(self.persist_dir, exist_ok= True)

        self.video_dir = os.path.join(self.persist_dir, self.video_id)
        faiss_path = os.path.join(self.video_dir, "faiss.index")
        metadata_path = os.path.join(self.video_dir, "metadata.pkl")
        self.results = None
    

        if not os.path.exists(faiss_path) or not os.path.exists(metadata_path):
            self._build_vectorstore()
            logging.info(f"[INFO] New vectorstore build for {self.video_id}")
        else:
            self.vectorstore = FaissVectorStore(video_id=self.video_id, persist_dir=self.video_dir)
            self.vectorstore.load()
            logging.info(f"[INFO] Existing vetorstore loaded for {self.video_id}")

        try:
            self.llm = ChatOpenAI(
                model=llm_model, 
                api_key=OPENAI_API_KEY,
                temperature=0
            )

            logging.info(f"[INFO] OpenAI chat model initialised: {llm_model}")
        except Exception as e:
            raise CustomException(e, sys)

    def _build_vectorstore(self):
        loader = DataLoader(url = self.url)
        video_data = loader.fetch_video_data()      # fetch transcript, preprocess the data and merge small segments
        chunks = loader.create_semantic_chunks(video_data=video_data)       # generate semantic chunks and save them in data folder
        embedding_manager = EmbeddingManager()
        embeddings = embedding_manager.generate_embeddings(chunks = chunks)     # generate embeddings
        embedding_manager.save_embeddings(embeddings=embeddings)         # save embeddings on disk

        self.vectorstore = FaissVectorStore(persist_dir=self.video_dir, video_id=None)
        self.vectorstore.add_embeddings(embeddings=embeddings)
        self.vectorstore.save()
        

    def search(self, query:str, top_k:int=5) -> List[str]:
        """
        Generates query embeddings using EmbeddingManager and search the vectorstore for closest vector to the query.
        Extracts metadata for the closest vectors and stores the text into a list
        """
        query_embedding = EmbeddingManager().embed_query(query = query)
        self.vectorstore.load()
        results = self.vectorstore.search(query_embedding=query_embedding, top_k=top_k)
        self.results = results
        texts = []

        for result in results:
            metadata = result.get("metadata") or {}
            if isinstance(metadata, dict):
                text = metadata.get("text") or ""
                if text:
                    texts.append(text)
        logging.info(f"[INFO] Query search completed. Relevant context extracted for query: {query}")
        return texts

    def generate_response(self, context:str, query:str) -> str:
        """
        Send context and query to to llm and returns results from llm
        Args: 
            context: relavant chunk text extracted using RAG search 
            query: user's query
        Returns: 
            llm result
        """
        # load prompt
        template = PromptTemplate(
            template = load_prompt("system_prompt"),
            input_variables = ['context', 'query']
        )

        prompt = template.format(context = context, query = query)
        logging.info(f"[INFO] Prompt with context and query loaded")

        result = self.llm.invoke(prompt)
        logging.info(f"[INFO] Response generated by llm for the query: {query[:15]}..")
        return result.content

    def get_video_timestamps(self) -> List[Tuple]:
        """
        Fetches timestamps in the form of tupple for each relavant chunk in order of their relavance and store them in the list. 
        Returns: Timestamps for all the chunks inside a list. Each timestamp is tuple (start, end)
        """
        try:
            logging.info(f"[INFO] Fetching timestamps for the reveant chunks")
            timestamps = []
            if not self.results is None:
                for item in self.results:
                    timestamps.append((item.get("metadata").get("start"), item.get("metadata").get("end")))
            logging.info(f"[INFO] Timestamps succesfully fetched")
            return timestamps
        except Exception as e:
            raise CustomException(e, sys)




